### ISSUE TITLE
IcopyX boot error

### ISSUE THREAD

**Issue by Reaper-Oni** [iCopy-X-Community/icopyx-teardown#2]
Recently my IcopyX gave a boot error during the boot sequence. The exact error is "Boot Timeout!". When I connect it through USB to a computer I hear it connecting, but the device doesn't show up as it should. I'm able to turn it off by holding the on/off button for a few seconds. 

Any suggestions?

**Comment by doegox** [comment]
if you didn't modify your device, contact their support

**Comment by Reaper-Oni** [comment]
Already got a new device through the supplier and IcopyX support doesn't seem to be responding since I'm still waiting for them to reply!

Initially I thought the OS for the IcopyX was located on the SD card, but that doesn't seem to be the case. I have no idea how to check where the OS is located or how to login on the device. I was hoping to find some help on researching this and fixing the boot timeout.
