### ISSUE TITLE
icopy-x , Capabilities structure version sent by Proxmark3 is not the same as the one used by the client! #28

### ISSUE THREAD

**Issue by lucyxss** [iCopy-X-Community/icopyx-teardown#3]
https://icopyx.com/

i try to install
1 way .brew install proxmark3

2 way.export HOMEBREW_PROXMARK3_PLATFORM=PM3ICOPYX && brew install proxmark3

3 way.brew install --with-generic proxmark3

➜ ~ proxmark3 /dev/tty.usbmodem21101
[=] Session log /Users/lucy/.proxmark3/logs/log_20220215.txt
[+] loaded from JSON file /Users/lucy/.proxmark3/preferences.json
[=] Using UART port /dev/tty.usbmodem21101
[!!] 🚨 Capabilities structure version sent by Proxmark3 is not the same as the one used by the client!
[!!] 🚨 Please flash the Proxmark with the same version as the client.
[!!] 🚨 ERROR: cannot communicate with the Proxmark

➜ ~ uname -a
Darwin zxldeMacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

**Comment by doegox** [comment]
yes, proxmark3 firmware and client in the icopy-x are much older than the proxmark3 repo.
you can flash the proxmark3, but beware the icopyx GUI won't work anymore as it expects the old version

**Comment by lucyxss** [comment]
how to get  matched proxmark3  client version. I want use proxmark3 or another client do some study

**Comment by doegox** [comment]
https://github.com/iCopy-X-Community/icopyx-teardown/tree/master/proxmark3#compiling-our-client
Use RRG/Iceman/master/v4.9237-1230-g804fef2a

**Comment by lucyxss** [comment]
Can provide a macos version client? I use RRG/Iceman/master/v4.9237 client always show me "[!!] 🚨 Capabilities structure version sent by Proxmark3 is not the same as the one used by the client!"


brew install proxmark3/4.9237 success

![image](https://user-images.githubusercontent.com/13196296/154100186-08a235b5-20de-462c-b2a2-7c49b1b6622c.png)


`➜  ~ /opt/homebrew/Cellar/proxmark3/4.9237/bin/proxmark3 /dev/tty.usbmodem21101
[=] Session log /Users/lucy/.proxmark3/log_20220215.txt
[=] Loading Preferences...
[+] loaded from JSON file /Users/lucy/.proxmark3/preferences.json
[=] Using UART port /dev/tty.usbmodem21101
[!!] 🚨 ERROR: cannot communicate with the Proxmark

➜  ~ /opt/homebrew/Cellar/proxmark3/4.9237/bin/proxmark3 /dev/tty.usbmodem21101
[=] Session log /Users/lucy/.proxmark3/log_20220215.txt
[=] Loading Preferences...
[+] loaded from JSON file /Users/lucy/.proxmark3/preferences.json
[=] Using UART port /dev/tty.usbmodem21101
[!!] 🚨 Capabilities structure version sent by Proxmark3 is not the same as the one used by the client!
[!!] 🚨 Please flash the Proxmark with the same version as the client.
[!!] 🚨 ERROR: cannot communicate with the Proxmark
`

**Comment by doegox** [comment]
no, I don't have OS X

**Comment by lucyxss** [comment]
Use RRG/Iceman/master/v4.9237-1230-g804fef2a

**Comment by Hamid-K** [comment]
Using the v.4.9237 (PLATFORM=PM3OTHER) from https://github.com/RfidResearchGroup/proxmark3/releases/tag/v4.9237 still leads to the same issue and error. Tested on both MacOS and Arch linux.

I noticed the hash commit g804fef2a mentioned above is no longer listed (maybe due to repo name change?). Could you kindly please provide link to an online fork with exact and compatible revision  that can be used?
